name: Godot CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Export
      id: export
      uses: firebelley/godot-export@v6.0.0
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
        relative_project_path: ./godot/failing
        presets_to_export: Web
        cache: true

    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
          path: ${{ steps.export.outputs.build_directory }}/Web

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4

  notify:
    runs-on: ubuntu-latest
    if: failure()
    needs: build-and-deploy
    steps:
    - name: Send Discord notification
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        content: |
            🔥🔥🔥 **FLEE! FLEE FOR YOUR LIVES! ABANDON YOUR POSTS!** 🔥🔥🔥
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        embeds: '[{"image": {"url": "https://images-ext-1.discordapp.net/external/9IqK1vVIJELe5nEUmdZjgm59iS3f6zBBqo_rzRXwLk4/https/media.tenor.com/TmMxoRQQnmMAAAPo/denethor-eating.mp4"}}]'